# Dependencies
markdown:         Kramdown
highlighter:      rouge
url:     https://raphael-werner.github.io 
baseurl:    "" 

# Setup
title:            Raphael Werner
description:      Research Assistant & PhD Student at Saarland University


author:
  name:           'Raphael Werner'

paginate:         5

# Custom vars

github:
  repo:           
