# Dependencies
markdown:         Kramdown
highlighter:      rouge
plugins: 	        [jekyll-paginate]

# Setup
title:            Raphael Werner
description:      'Research Assistant & PhD Student at Saarland University'
baseurl:          /


author:
  name:           'Raphael Werner'
paginate:         5
