# Dependencies
markdown:         Kramdown
highlighter:      rouge
plugins: 	        [jekyll-paginate]

# Setup
title:            Raphael Werner
description:      'Research Assistant & PhD Student at Saarland University'
url:              https://raphael-werner.github.io/
baseurl:          https://raphael-werner.github.io/


author:
  name:           'Raphael Werner'
paginate:         5
